name: auth
description: Auth Service
version: 1.0.1

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  conduit: ^4.4.0
  conduit_core: ^4.4.0
  conduit_postgresql: ^4.4.0
  jaguar_jwt: 3.0.0

dev_dependencies:
  lints: ^2.1.0
